version: "3.7"

services:
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://girts:secret@postgres:5432/smart-brain-docker
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api
  postgres:
    environment:
      POSTGRES_USER: girts
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    container_name: postgres
    build: ./postgres
    ports:
      - "5432:5432"
